apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demo-cert
  namespace: ingress-nginx
spec:
  secretName: demo-cert
  dnsNames:
#    - '*.<<DOMAIN>>'
    - '<<DOMAIN>>'
    - 'test1.<<DOMAIN>>'
    - 'test2.<<DOMAIN>>'
  issuerRef:
    name: lets-encrypt-issuer-prod
    kind: ClusterIssuer
    group: cert-manager.io
