apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lets-encrypt-issuer-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    preferredChain: "ISRG Root X1"
    email: my-demo-123@youremail.com
    privateKeySecretRef:
      name: lets-encrypt-issuer-prod-key # The operator will create this for us
    solvers:
    - dns01:
        cloudDNS:
          project: __PROJECT__ # Change to your project here
          serviceAccountSecretRef:
            name: gcp-cloud-dns-account-key
            key: service-account.json
